-- Callion applications table (Supabase / PostgreSQL)
-- Run this in the Supabase SQL editor.

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  company text not null,
  created_at timestamptz not null default now()
);

alter table public.applications
  add constraint applications_name_length check (char_length(name) between 1 and 120);

alter table public.applications
  add constraint applications_phone_length check (char_length(phone) between 5 and 32);

alter table public.applications
  add constraint applications_company_length check (char_length(company) between 1 and 160);

-- Service role key is used from the Node.js backend only.
-- Do not expose this table to the browser with a public anon key insert policy
-- unless you also add validation and rate limiting in Supabase.
